### ISSUE TITLE
Missing bluetooth adapter

### ISSUE THREAD

**Issue by Marko298** [SSMCD/bluetti2mqtt#1]
I have a bluetooth on my home assistant instance, but addon says that no adapters found. How I can tell him which adapter to use?

**Comment by Marko298** [comment]
<img width="1456" alt="CleanShot 2022-11-23 at 16 10 39@2x" src="https://user-images.githubusercontent.com/12628139/203567805-f03968bd-9c81-47c9-8e63-175a40378c5a.png">

**Comment by SSMCD** [comment]
Updated to map usb devices in version 1.0.3.

**Comment by Marko298** [comment]
thanks a lot!
