### ISSUE TITLE
problem with setting mqtt server to localhost

### ISSUE THREAD

**Issue by MegaBarf** [SSMCD/bluetti2mqtt#10]
Hi

I'm using the Mosquitto broker in HA. When I set the mqtt server to localhost or 127.0.0.1 i can't get a connection to the mqtt server from the script. When adding the actual IP adress or "homeassistant" it is working.

This is useful when you want the script run while you disconnect the ethernet.

I'm not sure if this is a problem of bluetti2mqtt but of Mosquitto broker but I'm not good enough to find out.

**Comment by MegaBarf** [comment]
I guess the answer is here:
"That’s not going to work. Your mqtt container has a different ip address since its a container.
And if you’re running ha also in a container, 127.0.0.1 would be the internal ip address of the container. You’ll need the ip address of your server and make sure ports are correctly open (seems to be the case from your docker command)"
see https://community.home-assistant.io/t/connect-to-local-mqtt/150018

any good ideas?

**Comment by SSMCD** [comment]
Please upgrade to version 1.2.0.  In the addon configuration page, leave all the MQTT settings blank.  This will force the addon to "auto-configure" MQTT and pull the necessary settings from Home Assistant.

I haven't tested it for your particular use case (disconnected from LAN).  If it still doesn't work, we can run the addon with the `host_network` [config variable](https://developers.home-assistant.io/docs/add-ons/configuration#optional-configuration-options) set to `true`.  That will dock the addon some security points so I wouldn't necessarily release that version to the public.

**Comment by MegaBarf** [comment]
I checked it over night, when ethernet is removed from my Pi the data still gets collected. Thank you.
