### ISSUE TITLE
Plugin configuration fails since last update

### ISSUE THREAD

**Issue by ast0815** [SSMCD/bluetti2mqtt#11]
Since the update to 1.2.0, I can no longer start the plugin or save the configuration. When I click the "save" button, I get this error message:

```
Failed to save add-on configuration, not a valid value. Got {'mqtt_username': 'bluetti', 'mqtt_password': 'redacted', 'mqtt_host': 'homeassistant.local', 'mqtt_port': 1883, 'bt_mac': 'C5:C1:52:36:C3:66', 'poll_sec': 120, 'ha_config': 'advanced', 'scan': False, 'debug': False, 'log': False}
```

**Comment by ast0815** [comment]
Setting all MQTT connection info to "" allowed me to save the config.

**Comment by steveheinsch** [comment]
Same issue here.

**Comment by SSMCD** [comment]
Sorry about that - I changed the schema for the MQTT port to a string thinking the configuration would update with the addon.  Sounds like it didn't.  

For anyone using the Mosquitto broker addon (I imagine most people are), you no longer need to configure the four MQTT fields (just leave them blank):

```
mqtt_username: ""
mqtt_password: ""
mqtt_host: ""
mqtt_port: ""
bt_mac: "00:11:22:33:44:55"
poll_sec: 30
ha_config: normal
scan: false
debug: false
log: false
```

If you are using an external MQTT broker, you will need re-enter the port number and resave the config.
