### ISSUE TITLE
[feature] power energy on dc input/output

### ISSUE THREAD

**Issue by fraucs** [SSMCD/bluetti2mqtt#12]
it would be useful to be able to see the input and the output of dc in the energy tab.

**Comment by SSMCD** [comment]
This add-on simply containerizes the [bluetti_mqtt](https://github.com/warhammerkid/bluetti_mqtt) package.  Any new features or functionality should be integrated there.

If you want to manually add energy sensors to Home Assistant, see [this post](https://diysolarforum.com/threads/monitoring-bluetti-systems.37870/page-5#post-633093) and [Integration - Riemann sum integral](https://www.home-assistant.io/integrations/integration/).
