### ISSUE TITLE
Add additional internal device fields

### ISSUE THREAD

**Issue by TheUser** [SSMCD/bluetti2mqtt#2]
Seems to me like it´s possible to add more data to Home Assistant automatically.

"
If you have configured Home Assistant to use the same MQTT broker, then by default most data and switches will be automatically configured there. This is possible thanks to Home Assistant's support for automatic MQTT discovery, which is enabled by default with the discovery prefix of homeassistant.

This can be controlled with the --ha-config flag, which defaults to configuring most fields ("normal"). Home Assistant MQTT discovery can also be disabled, or additional internal device fields can be configured with the "advanced" option.
"

Is it possible to add this --ha-config flag to the configuration so one could chose the "advanced" option if desired?

I would love to have it as I can see from the logs that there is for example pack voltage and cell voltage advertised from my ep500p.

Thanks in advance.

**Comment by SSMCD** [comment]
Added support for this in 1.0.4.

To get individual cell voltages you would need to edit [mqtt_client.py](https://github.com/warhammerkid/bluetti_mqtt/blob/main/bluetti_mqtt/mqtt_client.py) and configure MQTT discovery for that particular value - which is beyond the scope of this addon.  Currently, not every MQTT topic is set up for discovery in [bluetti_mqtt](https://github.com/warhammerkid/bluetti_mqtt).

Another option is to just manually configure an [MQTT sensor](https://www.home-assistant.io/integrations/sensor.mqtt/) in Home Assistant by adding it to your configuration.yaml.
