### ISSUE TITLE
Option 'log' does not exist in the schema for Bluetti to MQTT (ae139cbc_bluetti2mqtt)

### ISSUE THREAD

**Issue by mbay0r** [SSMCD/bluetti2mqtt#20]
Hi,

i have the following error in my supervisor log:

23-04-06 07:48:07 WARNING (MainThread) [supervisor.addons.options] Option 'log' does not exist in the schema for Bluetti to MQTT (ae139cbc_bluetti2mqtt)

maybe it is possible to fix this.

thank you!

**Comment by SSMCD** [comment]
Just remove 'log' from the addon configuration tab.  You will need to select 'Edit in YAML' from the three dot menu.  Or just hit 'Reset to Default.'

**Comment by mbay0r** [comment]
thank you.
