### ISSUE TITLE
Waiting for connection to ... start polling...

### ISSUE THREAD

**Issue by jaeger4** [SSMCD/bluetti2mqtt#23]
Hi!

Thanks for your great work first! I just have an issue - mostly after a few minutes I just get "Waiting for connection" in debug log:
2023-05-12 16:38:49 DEBUG    Waiting for connection to F3:85:XX:XX:XX:XX to start polling...

It's then only hanging in this endless "Waiting" state. If I restart the integration it's fine again for a few minutes. 

I am using a EB3A. RSSI is at -43 which should be not the problem. 

br, Christoph

**Comment by testehubgit** [comment]
I have the same issue. 
After a few minutes to hours - no connection. Only restart the add on helps. 
Same problem as described and solved previously here?

https://github.com/warhammerkid/bluetti_mqtt/issues/25


Thanks!
Christian

**Comment by warhammerkid** [comment]
I made some significant changes to `bluetti_mqtt` in version 0.14.0 that potentially would address this issue, although I've never heard of it just hanging there and not even printing out any error messages.

**Comment by SSMCD** [comment]
Updated the add-on to version 1.4.1 which now uses the latest bluetti-mqtt package [0.15.0]

**Comment by testehubgit** [comment]
Wow, fast response:)
Now it immediately reconnects after connection-loss. No need to restart the add on anymore!
For me it’s solved:)

thank you very much
Christian

**Comment by jaeger4** [comment]
Great job! I tested it now over 24 hours and it really works much better now. Over the time I see a crash of the add-on which was catched by watchdog and auto-started again. The "Delayed reconnect to F3:85:XX:XX:XX:XX after error" are well handled - reconnects after about 10 sec. 

Thanks a lot for the super fast fix! 

Best wishes,
Christoph
