### ISSUE TITLE
Not showing up in HA

### ISSUE THREAD

**Issue by steveheinsch** [SSMCD/bluetti2mqtt#3]
Brand new to HA, which I just recently installed ( Home Assistant 2023.1.5 Supervisor 2022.12.1 Operating System 9.4 Frontend 20230110.0 - latest). User has advanced permissions. Added repo per instructions via addon store/repositories. Don't see anything related to this addon after doing so. If I go back to "repositories", it shows "Bluetti2MQTT" installed, but I don't know how to access it. There isn't an icon added or anything on the addon page related to the addon and searching "bluetti" in the addons yields 0 results. I do have the warhammerkid/bluetti-mtqq tool already manually installed (and running) on that rpi4 which is providing data. I just wanted to more easily control it via HA and be sure it's always running in the background and restarts if there is an issue. What am I doing wrong?

**Comment by steveheinsch** [comment]
Thank you for the prompt reply. I guess that's where I'm stuck. The only place I see anything related to Bluetti2MQTT in HA is on the repo list page, and clicking on it there doesn't do anything (unless click on trash can to remove repo). I was thinking after adding the repo it would add an icon to the store like all others, such as grafana, that I would click to install it, but I don't see anything listed on the addon store page after adding the repo. There is nothing related under the "Official add-ons" section, "ESPHome" section or "Home Assistant Community Add-ons" section.

**Comment by steveheinsch** [comment]
Supervisor Log shows it installed...

23-01-18 11:54:23 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/SSMCD/bluetti2mqtt repository
23-01-18 11:54:25 INFO (MainThread) [supervisor.store] Loading add-ons from store: 69 all - 1 new - 0 remove

In addon store, using "search" function, for anything starting with "blu" including "Bluetti2MQTT" I get:
No results found in Official add-ons.
No results found in ESPHome
No results found in Home Assistant Community Add-ons.

**Comment by SSMCD** [comment]
Just tried it myself and it didn't show up until I cleared my app / browser cache.  Might be a bug in the latest HA version.

**Comment by steveheinsch** [comment]
Arg. Yep, that cleared it up. Thank you!

I noticed there isn't a port parameter in the config options - do you just append it to the MQTT host with a colon like 1.2.3.4:1883

**Comment by Spykylunique** [comment]
Hello,

config:
HA os 9.4
VM virtualbox

just to well understand:
I have data coming in the log but no entity created, how can i use the data?

'device_type': 'AC300', 'serial_number': xxxxxxxxx, 'arm_version': Decimal('4037.05'), 'dsp_version': Decimal('4036.02'), 'dc_input_power': 0, 'ac_input_power': 202, 'ac_output_power': 167, 'dc_output_power': 0, 'power_generation': Decimal('3.9'), 'total_battery_percent': 10, 'ac_output_on': True, 'dc_output_on': False}
{'ac_output

**Comment by SSMCD** [comment]
> I noticed there isn't a port parameter in the config options - do you just append it to the MQTT host with a colon like 1.2.3.4:1883

No, that will not work.  The port defaults to 1883.  I've added the port parameter to the config options page in version 1.0.5.


> I have data coming in the log but no entity created, how can i use the data?

The author of [bluetti_mqtt](https://github.com/warhammerkid/bluetti_mqtt) has chosen not to set up [MQTT Discovery](https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery/) for every available sensor (there are a lot of them).

If you would like to use the additional data values you can simply configure an [MQTT sensor](https://www.home-assistant.io/integrations/sensor.mqtt/) in Home Assistant by adding it to your configuration.yaml.

Another option is to  edit [mqtt_client.py](https://github.com/warhammerkid/bluetti_mqtt/blob/main/bluetti_mqtt/mqtt_client.py) and configure MQTT Discovery for that particular value - which is beyond the scope of this addon.

**Comment by steveheinsch** [comment]
>  I've added the port parameter to the config options page in version 1.0.5.

Thank you so much. Everything seems to be working just fine :)

**Comment by SSMCD** [comment]
It sounds like you've configured the Mosquitto broker correctly if you are seeing data in the logs.  Have you set up the Home Assistant [MQTT integration](https://www.home-assistant.io/integrations/mqtt/#configuration)?  That is how the data received by HA.

**Comment by Spykylunique** [comment]
> It sounds like you've configured the Mosquitto broker correctly if you are seeing data in the logs.  Have you set up the Home Assistant [MQTT integration](https://www.home-assistant.io/integrations/mqtt/#configuration)?  That is how the data received by HA.

Yes it's settup with 4 devices and also previous ac300 connection by shell command on the host system of the HA.
![image](https://user-images.githubusercontent.com/121767519/213666940-576f035d-18f3-41c0-aa1e-51a84bac2f14.jpeg)

But it wasn't working like a service so a lot of deconnection.

Why try to find a solution directly in HA with some automation to restart if need.

Below debug information of the Shell command on Windows 
![image](https://user-images.githubusercontent.com/121767519/213667458-73ea24a5-c90a-4e9e-8bdf-9f919230c45a.png)
![image](https://user-images.githubusercontent.com/121767519/213667485-19e5106c-82b2-4233-8f43-468a8260c35b.jpeg)
