### ISSUE TITLE
crashes if any one device is not found

### ISSUE THREAD

**Issue by steveheinsch** [SSMCD/bluetti2mqtt#5]
Everything is up to date.

I have 2 AC300's on different levels of the house. Normally everything runs fine. Occasionally though, one of them won't get picked up by rpi4 Bluetooth causing the plugin to crash and not autorestart even with the watchdog enabled. It tries several times then eventually permanently fails and have to manually click on "Start" again.

Is there a way to get it to continue to log the device it does find and silently continue to reconnect to any missing devices in the background? Perhaps a separate instance for each device? This can go unnoticed for quite awhile as there is no warning anything is wrong, unless you happen to go look at a dashboard that uses the sensors.

```
[19:52:55] INFO: Reading configuration settings...
Scanning....
Found AC3002141000XXXXXX: address 00:15:XX:XX:XX:XX
[19:53:05] INFO: Starting...
Could not find the given devices to connect to
2023-02-03 19:53:13 ERROR    Crashing with uncaught exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/server_cli.py", line 87, in start
    loop.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/server_cli.py", line 100, in run
    sys.exit('Could not find the given devices to connect to')
SystemExit: Could not find the given devices to connect to
2023-02-03 19:53:13 ERROR    Unhandled error in exception handler
context: {'message': 'Task exception was never retrieved', 'exception': SystemExit('Could not find the given devices to connect to'), 'future': <Task finished name='Task-1' coro=<CommandLineHandler.run() done, defined at /usr/local/lib/python3.10/site-packages/bluetti_mqtt/server_cli.py:92> exception=SystemExit('Could not find the given devices to connect to')>}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1781, in call_exception_handler
    self._exception_handler(self, context)
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/server_cli.py", line 136, in handle_global_exception
    asyncio.create_task(shutdown(loop))
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 336, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
/usr/local/lib/python3.10/asyncio/base_events.py:1788: RuntimeWarning: coroutine 'shutdown' was never awaited
  self.default_exception_handler({
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by SSMCD** [comment]
The watchdog is rate-limited to 10 restarts per 30 minute period.  After that the addon will shutdown until you hit Start again as you described.

You can create an automation to notify yourself when the addon is not running as described [here](https://www.youtube.com/watch?v=z3rBG0ioaPY).

The functionality to continue logging one device while the other is disconnected would need to be added to [bluetti_mqtt](https://github.com/warhammerkid/bluetti_mqtt) - suggest opening an issue there.

With this addon, you are limited to the Bluetooth range of your RPi4 running HassOS.  Depending on how far apart your two AC300s are, you may be better off running a separate instance of bluetti_mqtt on a second device, closer to the farthest Bluetti.

**Comment by steveheinsch** [comment]
@SSMCD Thank you, opened an issue with warhammerkid.
