### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Eyesupper** [SSMCD/bluetti2mqtt#6]
Hi 
I am having trouble installing, I keep getting “unrecognized arguments:” regarding MAC BT address for a Bluetti AC200Max. I have scanned and put in the correct BT Mac address for the AC200Max in configuration.

I am trying to install on a Pi with HA installed. Is there any specific software that needs to be install prior to installing bluetti2mqtt ?

Thank you for any help.

**Comment by SSMCD** [comment]
Might be a format issue.  Can you post your addon config yaml?

**Comment by Eyesupper** [comment]
Thank you for the reply.

This is the message, I have altered the MAC address, username and password. Sorry if this is not the correct info, I am new to this

Thank you for your help

[17:35:17] INFO: Reading configuration settings...
[17:35:20] INFO: Starting bluetti-mqtt...
usage: bluetti-mqtt [-h] [--scan] [--broker HOST] [--port PORT]
                    [--username USERNAME] [--password PASSWORD]
                    [--interval INTERVAL] [--ha-config {normal,none,advanced}]
                    [ADDRESS ...]
bluetti-mqtt: error: unrecognized arguments: 0X:XX:XX:XX:XX:XE
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped



Config Yami

mqtt_username: TheUserName
mqtt_password: ThePassword
mqtt_host: localhost
mqtt_port: 1883
bt_mac: 0X:XX:XX:XX:XX:XE
poll_sec: 30
ha_config: normal
scan: false
debug: false
log: false

**Comment by SSMCD** [comment]
Have you updated to version 1.0.7?  I've been unable to replicate the issue.

**Comment by SSMCD** [comment]
Please update to version 1.1.0 and let me know if the issue persists.

**Comment by Eyesupper** [comment]
Thank you for your help, 

Please see below

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Bluetti to MQTT
 MQTT bridge between Bluetti and Home Assistant
-----------------------------------------------------------
 Add-on version: 1.1.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.2.3
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[09:33:54] INFO: Reading configuration settings...
[09:33:56] INFO: Starting bluetti-mqtt...
usage: bluetti-mqtt [-h] [--scan] [--broker HOST] [--port PORT]
                    [--username USERNAME] [--password PASSWORD]
                    [--interval INTERVAL] [--ha-config {normal,none,advanced}]
                    [ADDRESS ...]
bluetti-mqtt: error: unrecognized arguments: 0X:XX:XX:XX:XX:XE
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Eyesupper** [comment]
Thank you for your help, finally working. I do not know how. I have done a clean install of everything and kept trying.
AC200 working fine.

Again
Thank you for your help
