### ISSUE TITLE
Bluetooth Proxy Compatibility

### ISSUE THREAD

**Issue by matthewhadley** [SSMCD/bluetti2mqtt#9]
I recently added some bluetooth proxies to home assistant via the esphome integration (https://esphome.github.io/bluetooth-proxies/). I was hoping that this integration could use the proxies to increase the bluetooth range of communicating to the Bluetti device, but this doesn't happen - do you know if it's possible?

**Comment by SSMCD** [comment]
As an _add-on_, I don't think it's currently possible to utilize Bluetooth proxies.  That would require a native Bluetooth _integration_.

I know such an integration was being developed at one point [here](https://github.com/warhammerkid/bluetti_mqtt/issues/23).  

This add-on was created as an interim method get Bluetti data into Home Assistant easily, without having to setup [bluetti_mqtt](https://github.com/warhammerkid/bluetti_mqtt) on a separate device.

Ultimately, a native integration will be a much cleaner and more functional way to communicate with Bluetti devices, especially with the extended range of Bluetooth proxies.

**Comment by matthewhadley** [comment]
Thanks for confirming. I found https://github.com/mariolukas/Bluetti_ESP32_Bridge useful when a separate (ESP32) device is an option.
